#!/bin/bash
#
# Name: gencert -- Utility to generate csr and self sign certificates.
# Author: Savitoj Singh
# Changelog: Mon Jun 05 2017 Savitoj Singh <savsingh@redhat.com>

usage="$(basename "$0") [-h] [-s, --selfsign] <fqdn> <csr_config>\n
Usage:\n

This script is used to generate key and CSR and self sign certificates.\n
\n
-h                      Show this help\n
-s, --selfsign  Generate self-signed certificate in addition to key and CSR.\n
<fqdn>          Output files will be named as <fqdn>.key and <fqdn>.csr.\n
<csr_config>            Path to file that specifies CSR information. Example config file available in project.\n
\n
"
if [[ $# -lt 2 ]]; then
   echo -e $usage
   exit 1
fi

if [[ $1 == --selfsign || $1 == -s ]]; then
# enable self sign flag
  SELF_SIGN=1
  shift
fi

FQDN=$1
CONFIG=$2

if [[ -z $FQDN ]]; then
   echo "FQDN/Name can not be of zero length"
   exit 2
fi

openssl req -config $CONFIG -new -sha512 -newkey rsa:4096 -nodes -keyout ${FQDN}.key -out ${FQDN}.csr -reqexts v3_req

echo "Created ${FQDN}.key"
echo "Created ${FQDN}.csr"

if [[ -n $SELF_SIGN ]]; then
  openssl x509 -req -days 365 -in ${FQDN}.csr -signkey ${FQDN}.key -out ${FQDN}.crt -extfile $CONFIG -extensions 'v3_req'
  echo "Created ${FQDN}.crt (self-signed)"
fi
